# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.CharField(help_text='Stores pageUrl', max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('expires', models.DateTimeField(null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('page_id', models.IntegerField(blank=True, default=0)),
                ('content', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('seo_description', models.TextField(blank=True)),
            ],
        ),
    ]
